name: ScheCPUMinecraft
version: '${project.version}'
main: de.emilschlampp.schecpuminecraft.ScheCPUMinecraft
api-version: '1.16'
commands:
  schecpu:
    permission: schecpuminecraft.command.base
permissions:
  schecpuminecraft.action.getbook:
    default: op
  schecpuminecraft.subcommand.examples:
    default: op
  schecpuminecraft.subcommand.getcodebook:
    default: op
  schecpuminecraft.subcommand.getcpublock:
    default: op
  schecpuminecraft.subcommand.getcpucontrol:
    default: op
  schecpuminecraft.subcommand.listcpu:
    default: op